name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          
      - name: Build for all platforms
        run: |
          GOOS=linux GOARCH=amd64 go build -o kanban-linux-amd64
          GOOS=windows GOARCH=amd64 go build -o kanban-windows-amd64.exe
          GOOS=darwin GOARCH=amd64 go build -o kanban-darwin-amd64
          GOOS=darwin GOARCH=arm64 go build -o kanban-darwin-arm64
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            kanban-linux-amd64
            kanban-windows-amd64.exe
            kanban-darwin-amd64
            kanban-darwin-arm64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
